version: '3'

services:
  nginx:
    image: nginx:stable
    environment:
      DOMAIN: ${DOMAIN}
      DIRECTORY: /app/public
    volumes:
      - ./docker/nginx/default.conf.template:/tmp/vhost.conf.template
      - ./var/log/nginx:/var/log/nginx
      - ./:/app
    command: /bin/sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /tmp/vhost.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - ${PROJECT_IP}:80:80
    depends_on:
      - php
    networks:
      default:

  php:
    build:
      context: docker/php
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    links:
      - db:db-container
      - rabbitmq:rabbitmq
    networks:
      default:
        aliases:
          - fpm

  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    volumes:
      - mysql-data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      default:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 57116:15672
      - 57115:5672
    networks:
      default:

volumes:
  mysql-data:

networks:
  default: